// schemas/cartSchema.js
import { z } from "zod";

export const CartSchema = z.object({
    CartID: z.string().optional(), // Assuming CartID is generated by the database and not provided by the client
    UserID: z.string(),
    TotalAmount: z.number().optional(), // TotalAmount might not be available in all requests
    CartItems: z.array(
        z.object({
            CartItemID: z.string().optional(), // Assuming CartItemID is generated by the database and not provided by the client
            ProductID: z.number(),
            Quantity: z.number(),
        })
    ),
});

export type CartSchemaType = z.infer<typeof CartSchema>;
